version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    ports: 
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SQL_DB}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_HOST: ${SQL_HOST}
      POSTGRES_PORT: ${SQL_PORT}
  python:
    build: .
    container_name: python
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: ${SQL_DB}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_HOST: ${SQL_HOST}
      POSTGRES_PORT: ${SQL_PORT}
    depends_on:
      - db

    
