-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS order_payments
(
    order_id character varying(45)[] NOT NULL,
    payment_sequential integer,
    payment_type character varying(32)[],
    payment_installments integer,
    payment_value numeric(3)[],
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS products
(
    product_id character varying(45)[] NOT NULL,
    product_category_name character varying(45)[],
    product_name_length numeric,
    product_description_length numeric,
    product_photos_qty numeric,
    product_weight_g numeric,
    product_length_cm numeric,
    product_height_cm numeric,
    product_width_cm numeric,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS order_reviews
(
    order_id character varying(45)[] NOT NULL,
    review_id character varying(45)[],
    review_score numeric,
    review_comment_title character varying(45)[],
    review_comment_message character varying(100)[],
    review_creation_date timestamp without time zone[],
    review_answer_timestamp timestamp without time zone,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS customers
(
    customer_id character varying(45)[] NOT NULL,
    customer_unique_id character varying(45)[],
    customer_zip_code_prefix numeric,
    customer_city character varying(45),
    customer_state character varying(45)[],
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS geolocation
(
    geolocation_zipcode_prefix numeric NOT NULL,
    geolocation_lat numeric,
    geolocation_lng numeric,
    geolocation_city character varying(45)[],
    geolocation_state character varying(45)[],
    PRIMARY KEY (geolocation_zipcode_prefix)
);

CREATE TABLE IF NOT EXISTS sellers
(
    seller_id character varying(45)[] NOT NULL,
    seller_zip_code_prefix numeric,
    seller_city character varying(45)[],
    seller_state character varying(3)[],
    PRIMARY KEY (seller_id)
);

CREATE TABLE IF NOT EXISTS order_items
(
    order_id character varying(45)[] NOT NULL,
    order_item_id numeric,
    product_id character varying(45)[],
    seller_id character varying(45)[],
    shipping_limit_date timestamp without time zone,
    price numeric,
    freight_value numeric,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id character varying(45)[] NOT NULL,
    customer_id character varying(45)[],
    order_status character varying(10)[],
    order_purchase_timestamp timestamp without time zone,
    order_approved_timestamp timestamp without time zone,
    order_delivered_carrier_date timestamp without time zone,
    order_delivered_customer_date timestamp without time zone,
    order_estimated_delivery_date timestamp without time zone,
    PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS geolocation
    ADD CONSTRAINT customers FOREIGN KEY (geolocation_zipcode_prefix)
    REFERENCES customers (customer_zip_code_prefix) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS sellers
    ADD FOREIGN KEY (seller_zip_code_prefix)
    REFERENCES geolocation (geolocation_zipcode_prefix) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS order_items
    ADD FOREIGN KEY (product_id)
    REFERENCES products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS order_items
    ADD FOREIGN KEY (seller_id)
    REFERENCES sellers (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT order_payments FOREIGN KEY (order_id)
    REFERENCES order_payments (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT order_reviews FOREIGN KEY (order_id)
    REFERENCES order_reviews (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT customers FOREIGN KEY (customer_id)
    REFERENCES customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT order_items FOREIGN KEY (order_id)
    REFERENCES order_items (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;